### ISSUE TITLE
Still working?

### ISSUE THREAD

**Issue by piec** [jugla/pyKeyAtome#1]
Hi,

Does it still work for you? I'm always getting 401 responses on [login](https://github.com/jugla/pyKeyAtome/blob/master/pykeyatome/client.py#L63-L68).
I'm using `pykeyatome -u <email> -p '<password>' live`. When I login to https://esoftlink.esoftthings.com/login I don't get a password error, but it redirects me to /login again, is it normal?

Thanks,
Pierre

**Comment by jugla** [comment]
Hello,
I perform the following command :  
`python __main__.py -u ATOME_USER -p ATOME_PASSWORD live`

My results : 
`
{
  "isConnected": true,
  "time": "2022-01-26T20:24:34+01:00",
  "last": 4154.0,
  "subscribed": 9000.0,
  "filteredPower": 4070.0,
  "timeLimitBeforePowerFailure": -1
}
`

If I use a wrong user or password, I get
`can only concatenate str (not "NoneType") to str`

**Comment by jugla** [comment]
The https://esoftlink.esoftthings.com/login is not intended to be used directly. That's why you are redirect to same page.

**Comment by jugla** [comment]
Error 401 suggets that you have no credentials for Atome ...

**Comment by jugla** [comment]
Please can you execute with `--debug` option.
`python __main__.py --debug -u ATOME_USER -p ATOME_PASSWORD live`

and gives output

**Comment by jugla** [comment]
I wonder if you have in your password a `,` or `"` or another special character that has meaning in json format

**Comment by piec** [comment]
Thank you, I was confused by the [login page](https://esoftlink.esoftthings.com/login).
I reset a password using that form and then used that password with pykeyatome, except this password seems completely unrelated to the api.
I'm using the correct password and it works fine now.
Thanks!
