### ISSUE TITLE
Cannot Login to API

### ISSUE THREAD

**Issue by sicknesz** [jugla/pyKeyAtome#2]
Hello, since 4pm today, i keep getting 401 from the API but i never changed my password and everything was fine before i updated homeassistant which triggered a reconnection which failed and since then i cannot connect back 

```
('Login error: Please check your username/password: %s ', '{"error":"Login failed"}')
```

Using the client.py from pykeyatome i get this : 
```
Message: 'Impossible to decode response: \nResponse was: [%s] %s'
Arguments: ("'id'", '401', '{"error":"Login failed"}')
can only concatenate str (not "NoneType") to str
```

Not sure if it's their API that's down again or if they changed something. 

Please accept my apologize if the problem is not on your side. 

Best Regards.

**Comment by jugla** [comment]
Sorry, 
I've not seen your issue.
Please can you tell me if the issue still occurs

**Comment by jugla** [comment]
It seems that your login is not valid

**Comment by jugla** [comment]
@sicknesz , please can you raise a new issue as your ticket it's quite old .
